### ISSUE TITLE
Use `ruleId` to differentiate between messages

### ISSUE THREAD

**Issue by davidtheclark** [wooorm/remark-validate-links#13]
![screen shot 2017-07-01 at 9 34 08 am](https://user-images.githubusercontent.com/628431/27763861-d14d6ff8-5e40-11e7-85e6-6bd11dce73e7.png)

Is this intentional?

**Comment by wooorm** [comment]
Oh, yeah, that’s intentional. Most projects emit different kinds of stuff, so it’s useful to note both the plugin (called `source`) and category (`ruleId`). This project only has one “category”, so `ruleId` and `source` are the same.

So, this is kind-off intentional. Do you have a suggestion for an alternative?

P.S. thought that just sprung to mind: we can also differentiate between non-existing file warnings and non-existing headings with the `ruleId`?

**Comment by davidtheclark** [comment]
Oh, this makes sense. I don't think it's clear to the user, though, when they are the same — certainly makes sense when they differ.

What do you think of having only one of them print if they are the same? I understand if not, and we can close this issue.

> P.S. thought that just sprung to mind: we can also differentiate between non-existing file warnings and non-existing headings with the ruleId?

This is a fine idea 👍

**Comment by wooorm** [comment]
Yeah you’re right. Do you feel it’s very important to do this soon? I think it should be in a major release, and I’m fine with that, but I can also bundle it with the next major release (although that could be in a while).

**Comment by davidtheclark** [comment]
Bundling it with a major release seems fine to me. No hurry!

**Comment by wooorm** [comment]
Should be published in a few minutes!
